language: generic
sudo: required

services:
    - docker


before_install:
    - docker build -t napatud/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true napatud/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker"
    env: "docker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-149592319634"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY